model_list:

  - model_name: ollama/codellama
    litellm_params:
      model: "ollama/codellama:34b"

  - model_name: mistral/mistral-medium
    litellm_params:
      model: mistral/mistral-medium-latest
      api_key: os.environ/MISTRAL_API_KEY
      api_base: https://api.mistral.ai/v1

  - model_name: openai/gpt-4-turbo-2024-04-09
    litellm_params:
      model: openai/gpt-4-turbo-2024-04-09
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/o1-mini
    litellm_params:
      model: o1-mini
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/o1-preview
    litellm_params:
      model: o1-preview
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/gpt-4o-2024-08-06
    litellm_params:
      model: gpt-4o-2024-08-06
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/o1-preview
    litellm_params:
      model: openai/o1-preview
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/gpt-3.5-turbo-0125
    litellm_params:
      model: openai/gpt-3.5-turbo-0125
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: openai/dall-e-3
    litellm_params:
      model: openai/dall-e-3
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://api.openai.com/v1

  - model_name: mistral/mistral-large
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: os.environ/MISTRAL_API_KEY
      api_base: https://api.mistral.ai/v1

  - model_name: anthropic/claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_base: https://api.anthropic.com/v1/messages
      api_key: os.environ/ANTHROPIC_API_KEY
      # explicit max_tokens required because a 256 default is being set otherwise
      max_tokens: 4000

  - model_name: anthropic/claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet-20240229
      api_base: https://api.anthropic.com/v1/messages
      api_key: os.environ/ANTHROPIC_API_KEY
      max_tokens: 4000

  - model_name: anthropic/claude-3.5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_base: https://api.anthropic.com/v1/messages
      api_key: os.environ/ANTHROPIC_API_KEY
      max_tokens: 4000

  - model_name: anthropic/claude-3-haiku
    litellm_params:
      model: claude-3-haiku-20240307
      api_base: https://api.anthropic.com/v1/messages
      api_key: os.environ/ANTHROPIC_API_KEY
      max_tokens: 4000

litellm_settings:
  drop_params: True
  stream: False

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  database_connection_pool_limit: 100
  database_connection_timeout: 60