model_list:
  - model_name: ollama/codellama
    litellm_params:
      model: "ollama/codellama"
  - model_name: openai/mistral-medium
    litellm_params:
      model: openai/mistral-medium-latest
      api_key: os.environ/MISTRAL_API_KEY
      api_base: https://api.mistral.ai/v1
  - model_name: mistral/mistral-large
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: os.environ/MISTRAL_API_KEY
      api_base: https://api.mistral.ai/v1
  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_base: https://api.anthropic.com/v1/messages
      api_key: os.environ/ANTHROPIC_API_KEY
litellm_settings:
  drop_params: True
  set_verbose: True